### ISSUE TITLE
new version / patch making change in EVERY file

### ISSUE THREAD

**Issue by caseybrookes** [ehmpathy/dynamodb-dao-generator#5]
whenever the version number is updated, ALL files have an irrelevant, annoying change in them. please make it stop.

**Comment by caseybrookes** [comment]
![image](https://github.com/ehmpathy/dynamodb-dao-generator/assets/58667871/1e37c52d-c793-4f94-9834-447b60220f2e)

**Comment by uladkasach** [comment]
done with https://github.com/ehmpathy/dynamodb-dao-generator/pull/7
